name: Main

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        run: |
          ls
      # - name: LS repo directory
      #   run: |
      #     ls ${{ github.workspace }}
      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"
